import Header from "@/components/layout/Header";
import "./styles/globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/components/layout/Footer";
import Notification from "@/components/common/Notification";
import { AllProvider } from "@/context/AllProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Trade",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AllProvider>
					<Header />
					<main>{children}</main>
					<Footer />
					<Notification />
				</AllProvider>
			</body>
		</html>
	);
}
